name: www.jiejiechen.com pipeline

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::773631419510:role/github-action-role
        role-session-name: githubactionsession
        aws-region: ap-southeast-2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: ./JiejieChenApp/ClientApp
      run: npm install

    - name: Run tests
      working-directory: ./JiejieChenApp/ClientApp
      run: npm run test:headless

    - name: Build
      working-directory: ./JiejieChenApp/ClientApp
      run: npm run build:prod

    - name: Deploy
      if: success()
      run: aws s3 sync ./JiejieChenApp/wwwroot s3://www.jiejiechen.com