# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and Deploy React Demo

on:
  push:
    branches:
      - feature/frontend-react
  workflow_dispatch:

jobs:
  build_spa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: yarn install, build, and test
        working-directory: jiejiechen-react
        run: |
          yarn install
          yarn lint
          yarn build

      - name: Zip artifact for deployment
        working-directory: jiejiechen-react
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: jiejiechen-react/release.zip

  deploy_spa:
    runs-on: ubuntu-latest
    needs: build_spa
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9FA47F97552F4422BE500E6F5DD90509 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73077CC6CC3A41ADB223AA216E66E9B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5155A9391D9343D69A6F9E85FDE00337 }}
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'react-demo-dev-spa'
          slot-name: 'Production'
          package: .
          

  build_web_api:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
  
      - name: Build with dotnet
        working-directory: services
        run: dotnet build --configuration Release

      - name: Test with dotnet
        working-directory: test/DemoApi.WebApi.Tests
        run: dotnet test
        
      - name: dotnet publish
        working-directory: services/DemoApi.WebApi
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/web_api
  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: web-api
          path: ${{env.DOTNET_ROOT}}/web_api
  
  deploy_web_api:
    runs-on: ubuntu-latest
    needs: build_web_api
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-web-api.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9FA47F97552F4422BE500E6F5DD90509 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73077CC6CC3A41ADB223AA216E66E9B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5155A9391D9343D69A6F9E85FDE00337 }}
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-api

      - name: Deploy to Azure Web App
        id: deploy-to-web-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'react-demo-dev-web-api'
          slot-name: 'production'
          package: .
          